# Generated by Django 5.0.1 on 2024-01-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_video', '0002_videocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='src',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
