# Generated by Django 4.2.3 on 2024-02-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_video', '0003_video_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
        migrations.DeleteModel(
            name='VideoComment',
        ),
    ]
