# Generated by Django 4.2.3 on 2024-02-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0002_univers_management_univers_email_univers_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='univers',
            name='karta',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
